import axios from "axios";
import html2canvas from "html2canvas";
import moment from "moment";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState, useRef } from "react";
import { ClimbingBoxLoader } from "react-spinners";
import namazData from "../namazdata.json";

export default function Home() {
  const [todayData, setTodaydata] = useState({});
  useEffect(() => {
    const date = moment().format("DD.MM.YYYY");
    const todayData = namazData.find((nd) => nd["MiladiTarihKisa"] === date);
    setTodaydata(todayData);
  }, []);

  const [yazi, setYazi] = useState("");
  const [kaynak, setKaynak] = useState("");
  const [error, setError] = useState("");

  const downloadRef = useRef(null);
  const containerRef = useRef(null);
  const [isMobile, setIsMobile] = useState(false);
  useEffect(() => {
    setIsMobile(/Mobi/i.test(window.navigator.userAgent));
  }, []);

  // useEffect(() => {
  //   const amount = document.body.offsetWidth / 1080;
  //   if (containerRef.current) {
  //     containerRef.current.style.transform = `scale(${amount})`;
  //   }
  //   window.addEventListener("resize", () => {
  //     const amount = document.body.offsetWidth / 1080;
  //     console.log(amount);
  //     containerRef.current.style.transform = `scale(${amount})`;
  //   });
  // }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isMobile ? (
        <div className="mobile">
          <div>
            <span>Working to be at mobile devices...</span>
            <ClimbingBoxLoader color="rgb(36, 177, 102)" />
          </div>
        </div>
      ) : (
        <main>
          <h2 className="title">AGD Ramazan Paylasim Generator</h2>
          <form
            action=""
            onSubmit={(e) => {
              e.preventDefault();
              if (!yazi || !kaynak) {
                document.body.scrollTo({ behavior: "smooth", top: 0 });
                document.documentElement.scrollTo({
                  behavior: "smooth",
                  top: 0,
                });
                setError("Yazı  girmeyi unuttunuz.");
                setTimeout(() => {
                  setError("");
                }, 3000);
                return;
              }
              html2canvas(document.querySelector(".container")).then(
                (canvas) => {
                  document.body.appendChild(canvas);
                  canvas.style.display = "none";
                  const a = document.createElement("a");
                  a.href = canvas.toDataURL("image/png");
                  a.download =
                    "agd-ramazan-" + moment().format("DD-MMMM-YYYY") + ".png";
                  document.body.appendChild(a);
                  a.click();
                  document.body.removeChild(a);
                }
              );
            }}
          >
            <div className="inputs">
              <label>Yazı</label>
              <textarea
                onChange={(e) => {
                  setYazi(e.target.value.trim().replace(/\n/g, " "));
                }}
              ></textarea>
              {error && (
                <div style={{ fontFamily: "MavenPro", color: "red" }}>
                  {error}
                </div>
              )}
              <label>Kaynak</label>
              <input
                onChange={(e) => {
                  setKaynak(e.target.value.trim().replace(/\n/g, "s"));
                }}
                type="text"
              ></input>
            </div>

            <div className="container" ref={containerRef}>
              <img src="/assets/images/hilal.png" alt="" className="bg-img" />
              <div className="top">
                <div className="date">
                  <div className="image">
                    <img src="/assets/images/calendar.png" alt="" />
                    <span id="date-hicri">
                      {todayData &&
                        todayData["HicriTarihUzun"]?.match(/^\d+/)[0]}
                    </span>
                  </div>
                  Ramazan <br />
                  1443
                </div>
                <div className="title">Ramazan</div>
                <div className="clocks">
                  <div className="iftar clock">
                    iftar <img src="/assets/images/switch-dark.png" alt="" />
                    <span id="iftar-clock">
                      {todayData && todayData["Aksam"]}
                    </span>
                  </div>
                  <div className="imsak clock">
                    imsak <img src="/assets/images/switch-light.png" alt="" />
                    <span id="imsak-clock">
                      {todayData && todayData["Imsak"]}
                    </span>
                  </div>
                </div>
              </div>
              <div className="content">
                <div id="text-content">{yazi}</div>
                <div className="source">
                  <div className="source-div">Kaynak</div>
                  <div className="source-div" id="source-content">
                    {kaynak}
                  </div>
                </div>
              </div>
              <div className="bottom flex-center">
                <img src="/assets/images/agd-logo.png" alt="" />
              </div>{" "}
            </div>

            <button
              className="downloadButton"
              onClick={(e) => e.stopPropagation()}
              type="submit"
            >
              Indir
            </button>
          </form>
        </main>
      )}
      <footer className="footer">
        {moment().format("YYYY")} © Made with ❤️{" "}
      </footer>{" "}
    </div>
  );
}
